#!/usr/bin/env python

# CAVEAT UTILITOR
#
# This file was automatically generated by TatSu.
#
#    https://pypi.python.org/pypi/tatsu/
#
# Any changes you make to it will be overwritten the next time
# the file is generated.

from __future__ import annotations

import sys

from tatsu.buffering import Buffer
from tatsu.infos import ParserConfig
from tatsu.parsing import Parser, isname, leftrec, nomemo, tatsumasu  # noqa
from tatsu.util import generic_main, re  # noqa

KEYWORDS = {}  # type: ignore


class Buffer(Buffer):
    def __init__(self, text, /, config: ParserConfig = None, **settings):
        config = ParserConfig.new(
            config,
            owner=self,
            whitespace=None,
            nameguard=None,
            comments_re=None,
            eol_comments_re=None,
            ignorecase=False,
            namechars="",
            parseinfo=False,
        )
        config = config.replace(**settings)
        super().__init__(text, config=config)


class Parser(Parser):
    def __init__(self, /, config: ParserConfig = None, **settings):
        config = ParserConfig.new(
            config,
            owner=self,
            whitespace=None,
            nameguard=None,
            comments_re=None,
            eol_comments_re=None,
            ignorecase=False,
            namechars="",
            parseinfo=False,
            keywords=KEYWORDS,
            start="wkt_representation",
        )
        config = config.replace(**settings)
        super().__init__(config=config)

    @tatsumasu()
    def _wkt_representation_(self):  # noqa
        pass

    @tatsumasu()
    def _point_text_representation_(self):  # noqa
        pass

    @tatsumasu()
    def _curve_text_representation_(self):  # noqa
        pass

    @tatsumasu()
    def _linestring_text_representation_(self):  # noqa
        pass

    @tatsumasu()
    def _circularstring_text_representation_(self):  # noqa
        pass

    @tatsumasu()
    def _compoundcurve_text_representation_(self):  # noqa
        pass

    @tatsumasu()
    def _surface_text_representation_(self):  # noqa
        pass

    @tatsumasu()
    def _curvepolygon_text_representation_(self):  # noqa
        pass

    @tatsumasu()
    def _polygon_text_representation_(self):  # noqa
        pass

    @tatsumasu()
    def _triangle_text_representation_(self):  # noqa
        pass

    @tatsumasu()
    def _collection_text_representation_(self):  # noqa
        pass

    @tatsumasu()
    def _multipoint_text_representation_(self):  # noqa
        pass

    @tatsumasu()
    def _multicurve_text_representation_(self):  # noqa
        pass

    @tatsumasu()
    def _multilinestring_text_representation_(self):  # noqa
        pass

    @tatsumasu()
    def _multisurface_text_representation_(self):  # noqa
        pass

    @tatsumasu()
    def _multipolygon_text_representation_(self):  # noqa
        pass

    @tatsumasu()
    def _polyhedralsurface_text_representation_(self):  # noqa
        pass

    @tatsumasu()
    def _tin_text_representation_(self):  # noqa
        pass

    @tatsumasu()
    def _geometrycollection_text_representation_(self):  # noqa
        pass

    @tatsumasu()
    def _linestring_text_body_(self):  # noqa
        pass

    @tatsumasu()
    def _curvepolygon_text_body_(self):  # noqa
        pass

    @tatsumasu()
    def _polygon_text_body_(self):  # noqa
        pass

    @tatsumasu()
    def _triangle_text_body_(self):  # noqa
        pass

    @tatsumasu()
    def _point_text_(self):  # noqa
        pass

    @tatsumasu()
    def _point_(self):  # noqa
        pass

    @tatsumasu()
    def _x_(self):  # noqa
        pass

    @tatsumasu()
    def _y_(self):  # noqa
        pass

    @tatsumasu()
    def _z_(self):  # noqa
        pass

    @tatsumasu()
    def _m_(self):  # noqa
        pass

    @tatsumasu()
    def _linestring_text_(self):  # noqa
        pass

    @tatsumasu()
    def _circularstring_text_(self):  # noqa
        pass

    @tatsumasu()
    def _compoundcurve_text_(self):  # noqa
        pass

    @tatsumasu()
    def _single_curve_text_(self):  # noqa
        pass

    @tatsumasu()
    def _curve_text_(self):  # noqa
        pass

    @tatsumasu()
    def _ring_text_(self):  # noqa
        pass

    @tatsumasu()
    def _surface_text_(self):  # noqa
        pass

    @tatsumasu()
    def _curvepolygon_text_(self):  # noqa
        pass

    @tatsumasu()
    def _polygon_text_(self):  # noqa
        pass

    @tatsumasu()
    def _triangle_text_(self):  # noqa
        pass

    @tatsumasu()
    def _multipoint_text_(self):  # noqa
        pass

    @tatsumasu()
    def _multicurve_text_(self):  # noqa
        pass

    @tatsumasu()
    def _multilinestring_text_(self):  # noqa
        pass

    @tatsumasu()
    def _multisurface_text_(self):  # noqa
        pass

    @tatsumasu()
    def _multipolygon_text_(self):  # noqa
        pass

    @tatsumasu()
    def _polyhedralsurface_text_(self):  # noqa
        pass

    @tatsumasu()
    def _tin_text_(self):  # noqa
        pass

    @tatsumasu()
    def _geometrycollection_text_(self):  # noqa
        pass

    @tatsumasu()
    def _empty_set_(self):  # noqa
        pass

    @tatsumasu()
    def _z_m_(self):  # noqa
        pass

    @tatsumasu()
    def _left_paren_(self):  # noqa
        pass

    @tatsumasu()
    def _right_paren_(self):  # noqa
        pass

    @tatsumasu()
    def _comma_(self):  # noqa
        pass

    @tatsumasu()
    def _number_(self):  # noqa
        pass


class Semantics:
    def wkt_representation(self, ast):  # noqa
        pass

    def point_text_representation(self, ast):  # noqa
        pass

    def curve_text_representation(self, ast):  # noqa
        pass

    def linestring_text_representation(self, ast):  # noqa
        pass

    def circularstring_text_representation(self, ast):  # noqa
        pass

    def compoundcurve_text_representation(self, ast):  # noqa
        pass

    def surface_text_representation(self, ast):  # noqa
        pass

    def curvepolygon_text_representation(self, ast):  # noqa
        pass

    def polygon_text_representation(self, ast):  # noqa
        pass

    def triangle_text_representation(self, ast):  # noqa
        pass

    def collection_text_representation(self, ast):  # noqa
        pass

    def multipoint_text_representation(self, ast):  # noqa
        pass

    def multicurve_text_representation(self, ast):  # noqa
        pass

    def multilinestring_text_representation(self, ast):  # noqa
        pass

    def multisurface_text_representation(self, ast):  # noqa
        pass

    def multipolygon_text_representation(self, ast):  # noqa
        pass

    def polyhedralsurface_text_representation(self, ast):  # noqa
        pass

    def tin_text_representation(self, ast):  # noqa
        pass

    def geometrycollection_text_representation(self, ast):  # noqa
        pass

    def linestring_text_body(self, ast):  # noqa
        pass

    def curvepolygon_text_body(self, ast):  # noqa
        pass

    def polygon_text_body(self, ast):  # noqa
        pass

    def triangle_text_body(self, ast):  # noqa
        pass

    def point_text(self, ast):  # noqa
        pass

    def point(self, ast):  # noqa
        pass

    def x(self, ast):  # noqa
        pass

    def y(self, ast):  # noqa
        pass

    def z(self, ast):  # noqa
        pass

    def m(self, ast):  # noqa
        pass

    def linestring_text(self, ast):  # noqa
        pass

    def circularstring_text(self, ast):  # noqa
        pass

    def compoundcurve_text(self, ast):  # noqa
        pass

    def single_curve_text(self, ast):  # noqa
        pass

    def curve_text(self, ast):  # noqa
        pass

    def ring_text(self, ast):  # noqa
        pass

    def surface_text(self, ast):  # noqa
        pass

    def curvepolygon_text(self, ast):  # noqa
        pass

    def polygon_text(self, ast):  # noqa
        pass

    def triangle_text(self, ast):  # noqa
        pass

    def multipoint_text(self, ast):  # noqa
        pass

    def multicurve_text(self, ast):  # noqa
        pass

    def multilinestring_text(self, ast):  # noqa
        pass

    def multisurface_text(self, ast):  # noqa
        pass

    def multipolygon_text(self, ast):  # noqa
        pass

    def polyhedralsurface_text(self, ast):  # noqa
        pass

    def tin_text(self, ast):  # noqa
        pass

    def geometrycollection_text(self, ast):  # noqa
        pass

    def empty_set(self, ast):  # noqa
        pass

    def z_m(self, ast):  # noqa
        pass

    def left_paren(self, ast):  # noqa
        pass

    def right_paren(self, ast):  # noqa
        pass

    def comma(self, ast):  # noqa
        pass

    def number(self, ast):  # noqa
        pass


def main(filename, **kwargs):
    pass


if __name__ == "__main__":
    import json

    from tatsu.util import asjson

    ast = generic_main(main, Parser, name="")
    data = asjson(ast)
    print(json.dumps(data, indent=2))
